import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

import '../models/vitals_model.dart';
import '../services/health_calculator.dart';

/// Export health report functionality
class HealthReportExporter {
  static Future<String> generateMarkdownReport({
    required String deviceId,
    required VitalSigns latestVitals,
    required List<HealthAlert> recentAlerts,
  }) async {
    final now = DateTime.now();
    final formatter = DateFormat('yyyy-MM-dd HH:mm');

    // Calculate health metrics
    final healthScore = HealthCalculator.calculateHealthScore(
      heartRate: latestVitals.heartRate,
      spo2: latestVitals.spo2,
      temperature: latestVitals.temperature,
      hrQuality: latestVitals.hrQuality,
      spo2Quality: latestVitals.spo2Quality,
    );

    final odi = HealthCalculator.calculateOxygenDeliveryIndex(
      heartRate: latestVitals.heartRate,
      spo2: latestVitals.spo2,
    );

    final buffer = StringBuffer();

    buffer.writeln('# Health Monitoring Report');
    buffer.writeln();
    buffer.writeln('**Device ID:** $deviceId');
    buffer.writeln('**Generated:** ${formatter.format(now)}');
    buffer.writeln();
    buffer.writeln('---');
    buffer.writeln();

    buffer.writeln('## Health Summary');
    buffer.writeln();
    buffer.writeln(
      '**Health Score:** ${healthScore.toStringAsFixed(0)}/100 - ${HealthCalculator.getHealthStatus(healthScore)}',
    );
    buffer.writeln();

    buffer.writeln('### Current Vital Signs');
    buffer.writeln();
    buffer.writeln('| Vital | Value | Status |');
    buffer.writeln('|-------|-------|--------|');
    buffer.writeln(
      '| Heart Rate | ${latestVitals.heartRate} BPM | ${_getHRStatus(latestVitals.heartRate)} |',
    );
    buffer.writeln(
      '| SpO2 | ${latestVitals.spo2}% | ${_getSpO2Status(latestVitals.spo2)} |',
    );
    buffer.writeln(
      '| Temperature | ${latestVitals.temperature.toStringAsFixed(1)}°C | ${_getTempStatus(latestVitals.temperature)} |',
    );
    buffer.writeln('| Battery | ${latestVitals.batteryPercent}% | - |');
    buffer.writeln();

    buffer.writeln('### Derived Metrics');
    buffer.writeln();
    buffer.writeln('- **Oxygen Delivery Index:** ${odi.toStringAsFixed(1)}');
    buffer.writeln(
      '- **Cardiovascular Efficiency:** ${HealthCalculator.calculateCardioEfficiency(heartRate: latestVitals.heartRate, spo2: latestVitals.spo2).toStringAsFixed(2)}',
    );
    buffer.writeln();

    buffer.writeln('### Signal Quality');
    buffer.writeln();
    buffer.writeln(
      '- **HR Quality:** ${latestVitals.hrQuality}% ${latestVitals.hasValidHR ? "✅" : "❌"}',
    );
    buffer.writeln(
      '- **SpO2 Quality:** ${latestVitals.spo2Quality}% ${latestVitals.hasValidSpO2 ? "✅" : "❌"}',
    );
    buffer.writeln();

    if (recentAlerts.isNotEmpty) {
      buffer.writeln('### Recent Alerts');
      buffer.writeln();
      for (final alert in recentAlerts.take(5)) {
        final time = DateFormat('HH:mm').format(alert.timestamp);
        buffer.writeln('- **[$time]** ${alert.severity}: ${alert.message}');
      }
      buffer.writeln();
    }

    buffer.writeln('---');
    buffer.writeln();
    buffer.writeln(
      '*This report was automatically generated by the Health Monitoring System.*',
    );
    buffer.writeln(
      '*Last reading: ${formatter.format(latestVitals.timestamp)}*',
    );

    return buffer.toString();
  }

  static String _getHRStatus(int hr) {
    if (hr == 0) return '⚠️ No reading';
    if (hr < 50) return '⚠️ Low';
    if (hr <= 100) return '✅ Normal';
    return '⚠️ High';
  }

  static String _getSpO2Status(int spo2) {
    if (spo2 >= 95) return '✅ Normal';
    if (spo2 >= 90) return '⚠️ Low';
    return '🔴 Critical';
  }

  static String _getTempStatus(double temp) {
    if (temp >= 36.5 && temp <= 37.5) return '✅ Normal';
    if (temp < 36.0) return '⚠️ Low';
    if (temp > 38.0) return '⚠️ High';
    return '⚠️ Abnormal';
  }
}

/// Dialog to show and share health report
Future<void> showHealthReportDialog({
  required BuildContext context,
  required String deviceId,
  required VitalSigns latestVitals,
  required List<HealthAlert> recentAlerts,
}) async {
  final report = await HealthReportExporter.generateMarkdownReport(
    deviceId: deviceId,
    latestVitals: latestVitals,
    recentAlerts: recentAlerts,
  );

  if (!context.mounted) return;

  showDialog(
    context: context,
    builder: (context) => AlertDialog(
      title: const Row(
        children: [
          Icon(Icons.description, color: Colors.blue),
          SizedBox(width: 8),
          Text('Health Report'),
        ],
      ),
      content: SizedBox(
        width: double.maxFinite,
        child: SingleChildScrollView(
          child: SelectableText(
            report,
            style: const TextStyle(fontFamily: 'monospace', fontSize: 12),
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.pop(context),
          child: const Text('Close'),
        ),
        FilledButton.icon(
          onPressed: () {
            // Copy to clipboard
            // Requires: import 'package:flutter/services.dart';
            // Clipboard.setData(ClipboardData(text: report));
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(content: Text('Report copied to clipboard!')),
            );
          },
          icon: const Icon(Icons.copy),
          label: const Text('Copy'),
        ),
      ],
    ),
  );
}
